XCFLAGS		= -m32 -DNEED_UI_LOOP_HOOK
XINCLUDES	+= -I$(topdir)/../gdb/sim/arm

XLDFLAGS=	$(topdir)/../gdb/sim/arm/libsim.a \
		$(topdir)/../gdb/opcodes/libopcodes.a \
		-lbfd -liberty \
		-Wl,-wrap,ARMul_OSHandleSWI
